# 🐍 Week 1 Notes: Python for Data Science
**DataScience@SMU**

---
Topics covered:
1. Python Basics (indexing, intervals, indentation, list comprehensions)
2. Environment Setup (virtual environments, package installation)
3. Pandas (DataFrames, selecting, filtering, column math, useful methods)
4. Linear Regression (concept, sklearn, nonlinear terms)

---
## 1. Python Basics

### Zero-Based Indexing
Python starts counting at **0**, not 1. The first item in a list is index 0.

In [ ]:
test = ["a", "b", "c"]

print(test[0])    # → 'a'
print(test[1])    # → 'b'
print(test[2])    # → 'c'
print(len(test))  # → 3

### Intervals: Left-Closed, Right-Open
The **left** endpoint is **included**; the **right** endpoint is **excluded**.

This is one of the most common gotchas in Python!

In [ ]:
print(list(range(0, 5)))  # → [0, 1, 2, 3, 4]  (5 is excluded)
print(list(range(5, 7)))  # → [5, 6]            (7 is excluded)

test = ["a", "b", "c"]
print(test[0:2]) # → ['a', 'b']        ('c' at index 2 is excluded)

[0, 1, 2, 3, 4]
[5, 6]
['a', 'b']

### Indentation
Python uses **spaces/indentation** to define code blocks — no curly braces like other languages.
Indentation must be consistent (typically 4 spaces).

In [2]:
for i in range(5):
    print(i)
    print(i * i)
    if i == 4:
        print("Hi")

0
0
1
1
2
4
3
9
4
16
Hi

### List Comprehensions
A compact way to write a `for` loop that returns a list. Much more Pythonic than building lists manually.

In [3]:
list_item = [1, 3, 6, 8, 10]

# Traditional for loop
stuff = []
for i in list_item:
    if i > 5:
        stuff.append(i + 1)
print("Loop result:", stuff)

# List comprehension (same result, one line)
stuff = [i + 1 for i in list_item if i > 5]
print("Comprehension result:", stuff)

# Dictionary comprehension uses {} instead of []
stuff_dict = {i: i + 1 for i in list_item if i > 5}
print("Dict comprehension:", stuff_dict)

Loop result: [7, 9, 11]
Comprehension result: [7, 9, 11]
Dict comprehension: {6: 7, 8: 9, 10: 11}

---
## 2. Environment Setup

> ⚠️ These commands are run in your **terminal**, not in a notebook cell.

### Virtual Environments
Keeps your project dependencies isolated — especially useful when different courses/projects need different package versions.

```bash
# Anaconda (recommended for data science)
conda activate <env_name>

# venv — Mac/Linux
source <name>/bin/activate

# venv — Windows
<name>\scripts\activate.bat
```

> ⚠️ **Never uninstall the system Python!** (Only Windows doesn't have one by default.)

---

### Installing Packages (Terminal)

```bash
# Install
python -m pip install <package>

# Upgrade
python -m pip install --upgrade <package>

# Version-specific install
python -m pip install <package>==1.1.0

# Anaconda-specific install
conda install <package>
```

> 💡 Use `python -m pip` (not just `pip`) to make sure you're installing into the correct environment. On Python 3 systems you may also need `pip3`.

---

### Key Libraries for Data Science

| Library | Purpose |
|---|---|
| `numpy` | Arrays and numerical operations |
| `scipy` | Math and science functions |
| `pandas` | Data manipulation and munging |
| `sklearn` | Machine learning models |
| `pytorch` | Neural networks |
| `tensorflow` | Neural networks (Google) |

---
## 3. Pandas

In [ ]:
import pandas as pd

# Create a sample DataFrame to use throughout this section
data = pd.DataFrame({
    'timestamp':['2011-08-20', '2011-08-23', '2011-08-27', '2011-09-01', '2011-09-05', '2011-09-06'],
    'full_sq':[43, 34, 43, 89, 77, 67],
    'life_sq': [27.0, 19.0, 29.0, 50.0, 77.0, 46.0],
    'floor': [4.0, 3.0, 2.0, 9.0, 4.0, 14.0],
    'price_doc': [5850000, 6000000, 5700000, 13100000, 16331452, 11000000]
})

data

    timestamp  full_sq  life_sq  floor  price_doc
0  2011-08-20       43     27.0    4.0    5850000
1  2011-08-23       34     19.0    3.0    6000000
2  2011-08-27       43     29.0    2.0    5700000
3  2011-09-01       89     50.0    9.0   13100000
4  2011-09-05       77     77.0    4.0   16331452
5  2011-09-06       67     46.0   14.0   11000000

### DataFrame Structure
- **Index**: the row labels (often integers, but can be anything — including text)
- **Columns**: named, can hold different data types per column
- Common dtypes: `int`, `float`, `object` (text), `datetime`

> ⚠️ Even if a column *looks* like a date, always verify with `.dtypes` — it may be stored as a plain string (object).

In [5]:
# DataFrame-level info
print(data.shape)       # (rows, cols) — no parentheses!
print(data.dtypes)      # data type of each column
print(data.columns)     # column names
print(data.index)       # row labels

(6, 5)
timestamp     object
full_sq        int64
life_sq      float64
floor        float64
price_doc      int64
dtype: object
Index(['timestamp', 'full_sq', 'life_sq', 'floor', 'price_doc'], dtype='object')
RangeIndex(start=0, stop=6, step=1)

In [6]:
# Summary statistics for all columns
data.describe()

         full_sq    life_sq      floor     price_doc
count   6.000000   6.000000   6.000000  6.000000e+00
mean   58.833333  41.333333   6.000000  9.663575e+06
std    22.021959  21.096603   4.604346  4.510669e+06
min    34.000000  19.000000   2.000000  5.700000e+06
25%    43.000000  27.500000   3.250000  5.887500e+06
50%    55.000000  37.500000   4.000000  8.500000e+06
75%    74.500000  49.000000   7.750000  1.257500e+07
max    89.000000  77.000000  14.000000  1.633145e+07

### Selecting Data: `.loc` vs `.iloc`

| Method | Selects by | Right endpoint |
|---|---|---|
| `.loc` | **Label** (column name, row label) | **Inclusive** |
| `.iloc` | **Integer position** | **Exclusive** |

In [7]:
# .loc — by label (rows 0–3 INCLUSIVE = 4 rows)
print(data.loc[0:3, ["timestamp", "full_sq"]])

print("---")

# .iloc — by position (rows 0–3 EXCLUSIVE = 3 rows)
print(data.iloc[0:3, 0:2])

    timestamp  full_sq
0  2011-08-20       43
1  2011-08-23       34
2  2011-08-27       43
3  2011-09-01       89
---
    timestamp  full_sq
0  2011-08-20       43
1  2011-08-23       34
2  2011-08-27       43

### Conditional Filtering

In [8]:
# Filter rows where full_sq > 43
print(data[data['full_sq'] > 43])

print("---")

# Filter rows AND select specific columns — must use .loc
print(data.loc[data['full_sq'] > 43, ['timestamp', 'floor']])

    timestamp  full_sq  life_sq  floor  price_doc
3  2011-09-01       89     50.0    9.0   13100000
4  2011-09-05       77     77.0    4.0   16331452
5  2011-09-06       67     46.0   14.0   11000000
---
    timestamp  floor
3  2011-09-01    9.0
4  2011-09-05    4.0
5  2011-09-06   14.0

### Column Math

In [9]:
# Element-wise math between columns
print(data['full_sq'] + data['life_sq'])

# Create a new column on the fly
data['ratio'] = data['full_sq'] / data['life_sq']
data[['full_sq', 'life_sq', 'ratio']]

0     70.0
1     53.0
2     72.0
3    139.0
4    154.0
5    113.0
dtype: float64

   full_sq  life_sq     ratio
0       43     27.0  1.592593
1       34     19.0  1.789474
2       43     29.0  1.482759
3       89     50.0  1.780000
4       77     77.0  1.000000
5       67     46.0  1.456522

### Useful Column Methods (return a single value)

In [16]:
(data['full_sq']).sum()

np.int64(353)

In [17]:
col = data['full_sq']  # Each column is a Series object — methods are called with .method()

print("sum:", col.sum())
print("mean:", col.mean())
print("std:", col.std())
print("median:", col.median())
print("mode:", col.mode()[0])

sum: 353
mean: 58.833333333333336
std: 22.02195873819281
median: 55.0
mode: 43

### Other Useful Methods

In [18]:
# isnull() — returns True/False Series for missing values
print(data['life_sq'].isnull())

# unique() — array of unique values
print(data['floor'].unique())

# value_counts() — count occurrences of each value
print(data['full_sq'].value_counts())

# str.contains() — True/False if string contains a match
print(data['timestamp'].str.contains('2011-09'))

0    False
1    False
2    False
3    False
4    False
5    False
Name: life_sq, dtype: bool
[ 4.  3.  2.  9. 14.]
full_sq
43    2
34    1
89    1
77    1
67    1
Name: count, dtype: int64
0    False
1    False
2    False
3     True
4     True
5     True
Name: timestamp, dtype: bool

---
## 4. Linear Regression

### Concept
Linear regression assumes the target (output) is a **weighted sum** of the input features:

$$price = m_1 \cdot full\_sq + m_2 \cdot life\_sq + m_3 \cdot floor + m_0$$

The model finds the best slope values ($m_1, m_2, ...$) by **minimizing a loss function** (default: Mean Squared Error).

### Interpretation
- **Positive slope** → direct relationship with target (feature goes up, target goes up)
- **Negative slope** → inverse relationship (feature goes up, target goes down)
- Normalize your data first if you want slopes to reflect *variable importance*
- Linear models are fast and highly interpretable

### Handling Nonlinear Terms
If a feature relationship is nonlinear (e.g., quadratic), create a new column and use it as the input:

$$y = m_0 + m_1 x_1 + m_2 x_2^2 \quad \Rightarrow \quad z = x_2^2, \quad y = m_0 + m_1 x_1 + m_2 z$$

In [21]:
# Nonlinear term example — substitute with a new column
data['floor_squared'] = data['floor'] ** 2
data[['floor','floor_squared']].head()

   floor  floor_squared
0    4.0           16.0
1    3.0            9.0
2    2.0            4.0
3    9.0           81.0
4    4.0           16.0

### sklearn Syntax

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = data[['full_sq', 'life_sq', 'floor']]
y = data['price_doc']

# Split into train/test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train model
lr = LinearRegression()
lr.fit(X_train, y_train)

# Predict
predictions = lr.predict(X_test)

# Inspect model
print("Coefficients (slopes):", lr.coef_)
print("Intercept (m0):", lr.intercept_)

Coefficients (slopes): [ 77775.71394339 164166.3597424   53546.22914483]
Intercept (m0):        -2512272.590384897

---
## Quick Reference Cheatsheet

| Task | Code |
|---|---|
| Index first item | `list[0]` |
| Slice (exclusive right) | `list[0:3]` |
| List comprehension | `[x+1 for x in lst if x > 5]` |
| Select by label | `df.loc[rows, cols]` |
| Select by position | `df.iloc[rows, cols]` |
| Filter rows | `df[df['col'] > val]` |
| New column | `df['new'] = df['a'] / df['b']` |
| Shape | `df.shape` |
| Data types | `df.dtypes` |
| Summary stats | `df.describe()` |
| Null check | `df['col'].isnull()` |
| Unique values | `df['col'].unique()` |
| Value counts | `df['col'].value_counts()` |
| Train model | `lr.fit(X, y)` |
| Predict | `lr.predict(X_test)` |
| Get slopes | `lr.coef_` |
| Get intercept | `lr.intercept_` |